# Generated by Django 4.2.1 on 2023-05-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ph', '0002_enderecobusca_latitude_enderecobusca_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='ip_host',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
