# Generated by Django 4.2.1 on 2023-06-25 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ph', '0005_alter_hosts_time_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enderecobusca',
            name='hosts',
        ),
        migrations.AddField(
            model_name='enderecobusca',
            name='host_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='ph.hosts'),
        ),
    ]
