# Generated by Django 4.2.1 on 2023-06-25 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ph', '0008_rename_host_id_enderecobusca_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enderecobusca',
            old_name='host',
            new_name='host_id',
        ),
    ]
