# Generated by Django 4.2.1 on 2023-06-25 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ph', '0011_remove_enderecobusca_host_enderecobusca_host_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecobusca',
            name='host_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='ph.hosts'),
        ),
    ]
