# Generated by Django 4.2 on 2023-07-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ph', '0013_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
